language: swift
osx_image: xcode11
script:
- xcodebuild -scheme CIRest -derivedDataPath CIRest.xcodeproj -destination 'platform=iOS Simulator,OS=12.0,name=iPhone 7' -enableCodeCoverage NO clean build test

